name: homezy
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.2.0
  curl_logger_dio_interceptor: ^0.0.3
  currency_text_input_formatter: ^2.1.8
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  equatable: null
  file_picker: ^5.2.4
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.15
  flutter:
    sdk: flutter
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  get_storage: ^2.0.3
  go_router: ^5.2.4
  google_fonts: ^3.0.1
  images_picker: ^1.2.11
  injectable: any
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  intl: any

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/homezy_logo.png"
  android: true
  ios: true

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/homezy_logo.png"
  


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
